name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: ✅ Checkout Project
        uses: actions/checkout@v4

      - name: 📐 Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      - name: 📐 Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: 🧪 Gradle Test
        run: |
          chmod +x ./gradlew
          ./gradlew test --info

      - name: 📦 Archive test reports (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/reports/tests/test
